spring.datasource:
  url: jdbc:postgresql://localhost:5432/testingres
  username: root
  password: root


spring.jpa.properties.hibernate:
  jdbc.lob.non_contextual_creation: true
  dialect: org.hibernate.dialect.PostgreSQLDialect
graphql:
  servlet:
    enpoint: /graphql
    enabled: true
    corsEnabled: true
    maxQueryDepth: 3
